name: Test GitHub Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: List project files and Git version
      run: |
          ls -ltr
          git --version
    - name: Check out Apache Tomcat
      uses: actions/checkout@v2
      with:
        repository: apache/tomcat # Repository name with owner
        ref: master               # The branch, tag or SHA to checkout
        path: ./tomcat            # Relative path under $GITHUB_WORKSPACE
