name: Test GitHub Actions

on: [push]                                                          # Workflow action

jobs:

  list:
    runs-on: ubuntu-latest                                          # Container image

    env:                                                            # Personal environment variables
      INIT: List project files

    steps:                                                          # Steps to run 
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: List project files
        run: |
          echo $INIT
          ls -ltr

  clone:
    runs-on: ubuntu-latest                                          # Container image
    needs: list

    steps:
      - name: Check my Personal web page
        uses: actions/checkout@v2
        with:
          repository: ChristianGrimberg/ChristianGrimberg.github.io   # Repository name with owner
          ref: master                                                 # The branch, tag or SHA to checkout
          path: ./ChristianGrimberg                                   # Relative path under $GITHUB_WORKSPACE

      - name: Compress downloaded repo
        run: |
          tar -czvf binary.tar.gz ./ChristianGrimberg/*.html

      - name: Upload compressed file
        uses: actions/upload-artifact@v3
        with:
          path: ./binary.tar.gz

  contents:
    runs-on: ubuntu-latest                                          # Container image
    needs: clone

    env:                                                            # Personal environment variables
      ARTIFACT: Shared data between jobs
      
    steps:                                                          # Steps to run
      - name: Download the artifact
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: List content of artifact
        run: |
          echo $ARTIFACT
          tar -ztvf ./binary.tar.gz
