name: Test GitHub Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: List project files and Git version
      run: |
          ls -ltr
          git --version
    - name: Check my Personal web page
      uses: actions/checkout@v2
      with:
        repository: ChristianGrimberg/ChristianGrimberg.github.io # Repository name with owner
        ref: master                                               # The branch, tag or SHA to checkout
        path: ./ChristianGrimberg                                 # Relative path under $GITHUB_WORKSPACE
    - name: List project files to see Tomcat files
      run: |
          ls -ltr ./ChristianGrimberg/
          echo "See web page notes!"
          cat ./ChristianGrimberg/index.md
