name: Test GitHub Actions

on: [push]                                                          # Workflow action

jobs:
  learning:
    runs-on: ubuntu-latest                                          # Container image

    env:                                                            # Personal environment variables
      INIT: List project files
      CHECK_WEB_PAGE: See my Personal web page notes
      ARTIFACT: Share data between jobs

    steps:                                                          # Steps to run 
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: List project files
        run: |
          echo $INIT
          ls -ltr

      - name: Check my Personal web page
        uses: actions/checkout@v2
        with:
          repository: ChristianGrimberg/ChristianGrimberg.github.io   # Repository name with owner
          ref: master                                                 # The branch, tag or SHA to checkout
          path: ./ChristianGrimberg                                   # Relative path under $GITHUB_WORKSPACE

      - name: Compress downloaded repo
        run: |
          tar -czvf binary.tar.gz ./ChristianGrimberg/*.html

      - name: Upload compressed file
        uses: actions/upload-artifact@v3
        with:
          path: ./binary.tar.gz

      - name: List checked project files and see web page notes
        run: |
          ls -ltr ./ChristianGrimberg/
          echo $CHECK_WEB_PAGE
          cat ./ChristianGrimberg/index.md
